export const TOGGLE_ANNOUNCEMENTS_LOADING = 'TOGGLE_ANNOUNCEMENTS_LOADING';

export const SET_ANNOUNCEMENTS_ERROR = 'SET_ANNOUNCEMENTS_ERROR';
export const CLEAR_ANNOUNCEMENTS_ERROR = 'CLEAR_ANNOUNCEMENTS_ERROR';

export const FETCH_ANNOUNCEMENTS_REQUEST = 'FETCH_ANNOUNCEMENTS_REQUEST';
export const FETCH_ANNOUNCEMENTS_FAILURE = 'FETCH_ANNOUNCEMENTS_FAILURE';
export const FETCH_ANNOUNCEMENTS_SUCCESS = 'FETCH_ANNOUNCEMENTS_SUCCESS';

