export const TOGGLE_ANNOUNCEMENTS_LOADING = 'TOGGLE_ANNOUNCEMENTS_LOADING';

export const SET_ANNOUNCEMENTS_ERROR = 'SET_ANNOUNCEMENTS_ERROR';
export const CLEAR_ANNOUNCEMENTS_ERROR = 'CLEAR_ANNOUNCEMENTS_ERROR';

export const FETCH_ANNOUNCEMENTS_REQUEST = 'FETCH_ANNOUNCEMENTS_REQUEST';
export const FETCH_ANNOUNCEMENTS_FAILURE = 'FETCH_ANNOUNCEMENTS_FAILURE';
export const FETCH_ANNOUNCEMENTS_SUCCESS = 'FETCH_ANNOUNCEMENTS_SUCCESS';

export const FETCH_ANNOUNCEMENT_COMMENTS_REQUEST = 'FETCH_ANNOUNCEMENT_COMMENTS_REQUEST';
export const FETCH_ANNOUNCEMENT_COMMENTS_FAILURE = 'FETCH_ANNOUNCEMENT_COMMENTS_FAILURE';
export const FETCH_ANNOUNCEMENT_COMMENTS_SUCCESS = 'FETCH_ANNOUNCEMENT_COMMENTS_SUCCESS';

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
