export const SET_DISCUSSIONS_ERROR = 'SET_DISCUSSIONS_ERROR';
export const CLEAR_DISCUSSIONS_ERROR = 'CLEAR_DISCUSSIONS_ERROR';

export const TOGGLE_DISCUSSIONS_LOADING = 'TOGGLE_DISCUSSIONS_LOADING';

export const LECTURE_DISCUSSION_REQUEST = 'LECTURE_DISCUSSION_REQUEST';
export const LECTURE_DISCUSSION_FAILURE = 'LECTURE_DISCUSSION_FAILURE';
export const LECTURE_DISCUSSION_SUCCESS = 'LECTURE_DISCUSSION_SUCCESS';

export const ADD_DISCUSSION_ENTRY_REQUEST = 'ADD_DISCUSSION_ENTRY_REQUEST';
export const ADD_DISCUSSION_ENTRY_FAILURE = 'ADD_DISCUSSION_ENTRY_FAILURE';
export const ADD_DISCUSSION_ENTRY_SUCCESS = 'ADD_DISCUSSION_ENTRY_SUCCESS';

export const GENERAL_DISCUSSION_REQUEST = 'GENERAL_DISCUSSION_REQUEST';
export const GENERAL_DISCUSSION_FAILURE = 'GENERAL_DISCUSSION_FAILURE';
export const GENERAL_DISCUSSION_SUCCESS = 'GENERAL_DISCUSSION_SUCCESS';


export const GENERAL_DISCUSSION_ENTRY_REQUEST = 'GENERAL_DISCUSSION_ENTRY_REQUEST';
export const GENERAL_DISCUSSION_ENTRY_FAILURE = 'GENERAL_DISCUSSION_ENTRY_FAILURE';
export const GENERAL_DISCUSSION_ENTRY_SUCCESS = 'GENERAL_DISCUSSION_ENTRY_SUCCESS';
