export const LECTURE_REQUEST = 'LECTURE_REQUEST';
export const LECTURE_SUCCESS = 'LECTURE_SUCCESS';
export const LECTURE_FAILURE = 'LECTURE_FAILURE';

export const SET_LECTURE_LOADING = 'SET_LECTURE_LOADING';

export const SET_LECTURE_ERROR = 'SET_LECTURE_ERROR';
export const CLEAR_LECTURE_ERROR = 'CLEAR_LECTURE_ERROR';

export const SECTIONS_REQUEST = 'SECTIONS_REQUEST';
export const SECTIONS_SUCCESS = 'SECTIONS_SUCCESS';
export const SECTIONS_FAILURE = 'SECTIONS_FAILURE';
