# Generated by Django 5.1.2 on 2024-10-30 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_courses_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='annoucement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('forum_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('thread_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.users')),
            ],
        ),
        migrations.AddField(
            model_name='chats',
            name='thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.thread'),
            preserve_default=False,
        ),
    ]
