# Generated by Django 5.1.2 on 2024-10-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_lecturer_annoucement_alter_enrollments_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='creator',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='student.users'),
            preserve_default=False,
        ),
    ]
