# Generated by Django 5.1.2 on 2024-10-30 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_forum_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.lecturer'),
        ),
    ]
