# Generated by Django 5.1.2 on 2024-10-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_course_resources_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_resources',
            name='resource_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
