# Generated by Django 5.1.2 on 2024-10-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_course_resources_resource_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
