# Generated by Django 5.1.2 on 2024-11-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_chats_upvote_thread_upvote_alter_thread_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='upvote',
            new_name='upvotes',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='upvote',
            new_name='upvotes',
        ),
    ]
