# Generated by Django 5.1.2 on 2024-11-04 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_rename_upvote_chats_upvotes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('lecture_name', models.CharField(max_length=100)),
                ('lecture_description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.courses')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.course_resources')),
            ],
        ),
    ]
