# Generated by Django 5.1.2 on 2024-11-05 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_resources',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='resource',
        ),
        migrations.AddField(
            model_name='course_resources',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.lecture'),
            preserve_default=False,
        ),
    ]
