# Generated by Django 5.1.2 on 2024-11-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_remove_course_resources_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image_thumbnails/'),
        ),
    ]
