# Generated by Django 5.1.2 on 2024-11-06 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_users_profile_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='student.users'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.thread'),
        ),
    ]
