# Generated by Django 5.1.2 on 2024-11-06 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_chats_receiver_alter_chats_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='student',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='student.users'),
            preserve_default=False,
        ),
    ]
