# Generated by Django 5.1.2 on 2024-11-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_remove_comment_student_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollments',
            name='course_id',
        ),
        migrations.AddField(
            model_name='enrollments',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='course',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='student.courses'),
            preserve_default=False,
        ),
    ]
