# Generated by Django 5.1.2 on 2024-11-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_remove_enrollments_course_id_enrollments_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='users',
            name='profile_image_thumbnail',
        ),
        migrations.AddField(
            model_name='users',
            name='pictureId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='pictureURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='picturethumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
