# Generated by Django 5.1.2 on 2024-11-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_remove_users_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='picturethumbnail',
            new_name='pictureThumbnail',
        ),
    ]
