# Generated by Django 5.1.2 on 2024-11-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
