# Generated by Django 5.1.2 on 2024-11-14 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_blacklistedtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=100)),
                ('chapter_description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.courses')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='chapter',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='student.chapter'),
            preserve_default=False,
        ),
    ]
