# Generated by Django 5.1.2 on 2024-11-18 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_remove_lecture_course_chapter_lecture_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='course',
        ),
        migrations.AddField(
            model_name='forum',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.lecture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='thread_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='chat_counts',
            field=models.IntegerField(default=0),
        ),
    ]
